### ISSUE TITLE
Typescript ParseResult Type

### ISSUE THREAD

**Issue by thewordisbird** [Bunlong/react-papaparse#97]
With headers set to true in the config for the CSVReader component, the ParseResult type for the data doesn't match the provided output when the config prop has `{header: true}`. This is described in "The Parse Result Object" section of the docs:

> data is an array of rows. If header is false, rows are arrays; otherwise they are objects of data keyed by the field name.

but is not addressed in the type definition as the ParseResult interface only provides a data type  of T[] for the ParseResult Object data and has no option for the T type of the ParseResult Object data when header is true.

**Comment by Bunlong** [comment]
@thewordisbird It's was fixed. Please install the last version `3.18.0`. Thanks!

**Comment by gogog22510** [comment]
I still have this issue using 3.18.0. The return type complained by the compiler is still T[]. Any suggestion?
